name: "FarmCraft"
author: TheTealViper
version: "1.21.0.b.2"
api-version: "1.21"
description: "Custom farming"
main: me.TheTealViper.farmcraft.FarmCraft
softdepend: [DecentHolograms]
commands:
  farmcraft: