name: "FarmCraft"
author: TheTealViper
version: "1.20.1.a.2"
api-version: "1.19"
description: "Custom farming"
main: me.TheTealViper.farmcraft.FarmCraft
softdepend: [DecentHolograms]
commands:
  farmcraft: