name: "FarmCraft"
author: TheTealViper
version: "1.20.4.a.1"
api-version: "1.19"
description: "Custom farming"
main: me.TheTealViper.farmcraft.FarmCraft
softdepend: [DecentHolograms]
commands:
  farmcraft: