name: "FarmCraft"
author: TheTealViper
version: "1.20.1.a.1"
api-version: "1.20"
description: "Custom farming"
main: me.TheTealViper.farmcraft.FarmCraft
softdepend: [HolographicDisplays,DecentHolograms]
commands:
  farmcraft: